# Generated by Django 3.1 on 2021-04-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=20)),
                ('pre_do_no', models.CharField(max_length=20)),
                ('delivery_order_no', models.IntegerField(blank=True, null=True)),
                ('net_weight_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('weight_out_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
