# Generated by Django 3.1 on 2021-04-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shipment_id',
            field=models.CharField(max_length=20, verbose_name='เลขชิปเมนท์'),
        ),
    ]
