# Generated by Django 3.1 on 2021-04-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20210407_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='net_weight_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
